#!/usr/bin/env python3
"""Stamp Steep's provenance header onto a copy of index.html for the site repo.

    sync_steep.py <source index.html> <destination path> <sha> [date]

Writes the destination and reports whether anything meaningful changed. The
comparison ignores the header itself, so a re-run on an unchanged timer does not
manufacture a commit whose only difference is today's date.

Prints `changed=true|false` to $GITHUB_OUTPUT when running under Actions, and a
human-readable line either way.
"""
import datetime
import io
import os
import sys

DOCTYPE = "<!doctype html>"

HEADER = """<!doctype html>
<!--
  Steep — a tea and coffee timer that flashes when time is up. Single-file copy.

  Synced {date} from github.com/arnaudin/tea-timer @ {sha}, by that repo's
  .github/workflows/sync-to-site.yml. Do not edit this file: edit the source and
  the next push overwrites this copy.

  No front matter, so Jekyll passes it through untouched. No build, no
  dependencies; the only network request is the Google Fonts stylesheet.
-->"""


def body_of(text):
    """The document after any leading doctype and provenance comment."""
    if not text.startswith(DOCTYPE):
        return text
    rest = text[len(DOCTYPE):]
    if rest.lstrip().startswith("<!--"):
        end = rest.find("-->")
        if end != -1:
            return rest[end + 3:]
    return rest


def main():
    if len(sys.argv) not in (4, 5):
        sys.exit(__doc__)
    src_path, dst_path, sha = sys.argv[1:4]
    date = sys.argv[4] if len(sys.argv) == 5 else datetime.date.today().isoformat()

    source = io.open(src_path, encoding="utf-8").read()
    if not source.startswith(DOCTYPE):
        sys.exit("refusing to sync: %s does not start with %s" % (src_path, DOCTYPE))
    if source.lstrip().startswith("---"):
        sys.exit("refusing to sync: %s has front matter; Jekyll would render it" % src_path)

    body = body_of(source)
    new = HEADER.format(date=date, sha=sha) + body

    try:
        old = io.open(dst_path, encoding="utf-8").read()
    except IOError:
        old = None

    changed = old is None or body_of(old) != body

    if changed:
        os.makedirs(os.path.dirname(dst_path), exist_ok=True)
        io.open(dst_path, "w", encoding="utf-8").write(new)

    print("changed" if changed else "no change: the copy already matches the source")

    out = os.environ.get("GITHUB_OUTPUT")
    if out:
        with io.open(out, "a", encoding="utf-8") as fh:
            fh.write("changed=%s\n" % ("true" if changed else "false"))


if __name__ == "__main__":
    main()
